### PR TITLE
Introduction

### PR DESCRIPTION
**Pull request by legithubble**
add a fun fact and names

### CODE REVIEW

**Review by jordanlianhs — CHANGES_REQUESTED** [review]
Please change name :D

**Review by JinxYi — CHANGES_REQUESTED** [review]
change the names

**Review by jordanlianhs — APPROVED** [review]
LGTM 🚀 🚀 🚀 🚀

**Review by JinxYi — COMMENTED** [review]
yay

**Review by JinxYi — APPROVED** [review]
yay

**Pull request merged**
